<?php
/**
* @file
* Custom FAPI payment info with validation + submission.
*
* Creates a box with a link to a custom page: `submit-ad`.
* `submit-ad` page determines your role:
*   - Anon users can login or register an account.
*     (Based on LoginToboggan unified login page.)
*   - 'Submit Ad' & other 'Authenticated' users go straight ad creation.
*  Add custom jQuery price checker with a PHP price check.
*   - the PHP is the absolute truth and the one that is saved.
*
* @TODO
* - Live test CC Submit Handler!
* - Take over or give up and let LoginToboggan take over the login.
*/
define ('DEBUG', TRUE);

/**
* Implementation of HOOK_menu
*/
function ad_payment_menu() {
  $items['submit-ad'] = array(
    'title'           => 'Submit Classified Ad',
    'access callback' => TRUE,
    'page callback'   => 'ad_payment_ad_submit_form_page',
    'type'            => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function ad_payment_ad_submit_form_page() {

  global $user;
  
  if (!$user->uid) {
    // Use this code if you want LoginToboggan 
    //  to take over completely the login process.
    // This will result in the login form 
    //  defaulting to 'login' rather than 'register'.
    
    // module_load_include('logintoboggan', 'logintoboggan');
    // $content = logintoboggan_unified_login_page('login');
  
    // Cut and paste from LoginToboggan.
    $register_form = drupal_get_form('user_register_form');
    $rendered_login_form = drupal_render($login_form);
    $rendered_register_form = drupal_render($register_form);
    $variables = array(
      'login_form'    => $rendered_login_form,
      'register_form' => $rendered_register_form,
      'active_form'   => $active_form,
    );
    $content = theme('lt_unified_login_page', $variables);
  }
  elseif (in_array('submit ad', $user->roles) || in_array('authenticated user', $user->roles)) {
    // Get Node Creation Form.
    module_load_include('inc', 'node', 'node.pages');
    $content = node_add('ad_s');
  }
  
  return $content;
}

/**
* Implementation of hook_block_info
*/
function ad_payment_block_info() {
  $blocks['ad_payment_create_ad'] = array(
    'info'       => 'Submit Classified Ad',
    'status'     => 1,
    'visibility' => 0,
    'region'     => 'sidebar_first',
    'pages'      => 'ad/*',
  );
  
  return $blocks;
}

/**
* Implementation of hook_block_view
*
*/
function ad_payment_block_view($delta = '') {
  $block = array();
  
  switch ($delta) {
    case 'ad_payment_create_ad':
      $block['subject'] = '<none>';
      $block['content'] = l('Submit Ad', 'submit-ad');
      break;
  }
  return $block;
}

/**
* Implementation of HOOK_form_alter()
*
* Alter form to increase legibility and flow.
* - Insert a modular Price block for both PHP and jQuery pricing.
* - Hide 'Submit', 'Preview', and 'Delete' until completed form.
* - Insert CC Form in the Last Step.
* - Correct Validation errors by step.
*/
function ad_payment_form_ad_s_node_form_alter(&$form, &$form_state, $form_id) {
  dsm('Form Alter');
  

  // Hide SUBMIT AND PREVIEW
  // $form['actions']['save']['#access']    = FALSE;
  # $form['actions']['preview']['#access'] = FALSE;
  # $form['actions']['delete']['#access']  = FALSE;

    // Change Save to Submit.
    $form['actions']['save']['#value']  = 'Submit Ad';
    
    // Insert CC Validation.
    $form['#validate'][] = '_ad_payment_cc_validate';
    $form['#submit'][]   = '_ad_payment_cc_submit';
    
    // Float First 2 Groups.
    $form['#fieldgroups']['group_ad']->weight = -20;
    $form['#fieldgroups']['group_upgrade']->weight = -10;

    module_load_include('inc', 'ad_payment', 'ad_payment_form');
    ad_payment_form($form, $form_state);
    
  if(DEBUG) {
    global $user;
    dsm('USER');
    dsm($user);
    dsm('FORM');
    dsm($form);
    dsm('FORM STATE');
    dsm($form_state);
    dsm('FORM-STATE : NODE');
    dsm($form_state['node']);


  }
  //  Ad Price
  module_load_include('inc', 'ad_payment', 'ad_payment_price_check');
  $total_price = ad_payment_price_check($form_state, 'form_state'); 
  $form['field_price']['#default_value'] = $total_price;
  dsm('TOTAL PRICE - ' . $total_price);
  $ad_price = ($total_price == '0.00') ? 'Current Price: $0' : _ad_payment_form_price_display($form_state);
  
  $form['field_price_check'] = array(
    '#prefix' => '<div id="ad-price-box">',
    '#markup' => 'Total Price $' . $total_price,
    '#weight' => -200,
    '#suffix' => '</div>',
  );
}


/** 
* Custom CC Validation.
*/
function _ad_payment_cc_validate(&$form, &$form_state) {
  // Check CC Data
  module_load_include('inc', 'ad_payment', 'ad_payment_cc_validate');
  _ad_payment_validate_cc_data($form_state);
  
  // Get Price
  module_load_include('inc', 'ad_payment', 'ad_payment_price_check');
  $ad_price = ad_payment_price_check($form_state, 'form_state');
  dsm('AD PRICE (cc_validate) ----- ' . $ad_price);
  form_set_value($form['field_price'], $ad_price, &$form_state);  
}

/**
* Custom CC Submit Handler.
*
* Submit data to Netidea.
* Retrieve CCID and feed it into Ad_Payment module to link the two.
*/
function _ad_payment_cc_submit($form, $form_state) {

#  dsm('CC Submit Handler.');
 
  
  $values = $form_state['values'];
  $node   = $form_state['node'];
  $price  = $form_state['storage']['price'];
  
  $card_type = ($values['field_card_type'] == 0) ? 'Visa' : 'Mastercard';
  // // Submit Data to Netidea
  // // Commented Out Until Live test
  
  // define ('VALIDATION_TEST_MODE', FALSE);
  // Following require needs to be enabled to function.
  //  require_once ('classifieds.db.php');
  // /* The CVVID is optional and can be omitted */
  // $ccid = updateDatabase(
  //  $values['field_first_name'] . ' ' . $values['field_last_name'],    // $_POST['name'], 
  //  $values['email'],    // $_POST['email'], 
  //  $card_type,    // $_POST['card_type'], 
  //  $values['field_cc_number'],    // $_POST['card_number'], 
  //  $values['field_exp_month'] . '/' . $values['field_exp_year'],    // $card_expiry, 
  //  // NULL    // #$_POST['card_cvvid']);   
  //  $values['field_exp_phone'],    // $_POST['phone']);   
  // );
  //
  // /* You'll probably want to just email this link instead. */
  // #$url = sprintf('https://www.pennywiseads.com/admin/orders.php?action=view&id=%d', $ccid);    
  // #print "Order <a href='$url'>#$id</a> saved.";

  // Set CCID
  $ccid = rand();
  form_set_value($form['field_ccid'], $ccid, &$form_state);  

}

function ad_payment_node_insert($node) {
#  dsm('NODE INSERT');
#  dsm($node);
  
  // $cc_num = ($values['field_cc_num']) ? $values['field_cc_num'] : '1234';
  // Get Price
  module_load_include('inc', 'ad_payment', 'ad_payment_price_check');
  $ad_price = ad_payment_price_check($node, 'node');
  
   $nid = db_insert('adp')->fields(array(
    'ccid'    => ($node->field_ccid['und'][0]['value']) ? $node->field_ccid['und'][0]['value'] : rand(),
    'uid'     => $node->uid,
    'nid'     => $node->nid,
    'cc_type' => ($node->field_card_type == 0) ? 'MasterCard' : 'Visa',
    'exp_m'   => $node->field_exp_month,
    'exp_y'   => $node->field_exp_year,
    'cc_num'  => substr($node->field_cc_number, -4),
    'price'   => $ad_price,
    'created' => $node->created,
  ))->execute();  
  
  
  // Becuase Life isn't just.
  // You need to update the newly created node with correct data.
  
}

/**
* Ad Price Display Theme Registration.
* 
* @param $form_state['storage']['price']
*   
* @return
*   HTML output for form display.
*/
function _ad_payment_form_price_display($form_state) {
  $price = $form_state['storage']['price'];
  if(!$price) {
    return;
  }
  
  // Ad Copy
  $ad_copy = check_plain($form_state['node']->field_ad_copy['und'][0]['value']);

  // Liveload
  $ad_status = ($price['options']['liveload'] == TRUE) ? 'Liveload Classified Ad' : 'Classified Ad';
  
  // Areas
 if (is_array($form_state['node']->field_area['und'])) {
   foreach($form_state['node']->field_area['und'] as $area) {
     $areas .= ' ' . $area[0];
   }
 }  
  // Rate
  $rate = ($price['rate']['term_rate'] == 0) ? 'Personal' : 'Business';
  
  // Ad Taxonomy
  $classification = $price['rate']['term'];
  $section = $price['rate']['rate_name'];
  
  // Ad Price
  $discount = ($price['areas'] == 4) ? ' <br/><em>With $2 Discount for booking all four areas! </em>' : '';
  $ad_price = '$' . $price['total'];
  
  // Output Display 
  // THIS NEEDS TO BE THEMED!
  $ad_review = 
    '<dl>' .
    '<lh>Ad Copy:</lh><dt>' . $ad_copy . '</dt>' . 
    '<lh>Ad Type:</lh><dt>' . $ad_status . '</dt>' . 
    '<lh>Publication In <strong>' . $price['areas'] . '</strong> Area(s): </lh><dt> ' . $areas . ' </dt>' . 
    '<lh>Classification:</lh><dt>' . $classification . ' (' . $section . ' rated)</dt>' . 
    '<lh class="ad_price">Price:</lh><dt> <strong>' . $ad_price . '</strong>' . $discount . '<dt>' .
    '</dl>';

  return $ad_review;

}

