; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[views_bulk_operations][version] = "3.1"

projects[addanother][version] = "2.1"

projects[addressfield][version] = "1.0-beta4"

projects[admin_menu][version] = "3.0-rc4"

projects[advanced_help][version] = "1.0"

projects[aes][version] = "1.5"

projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][version] = "2.7"

projects[better_exposed_filters][version] = "3.0-beta3"

projects[boost][version] = "1.0-beta2"

projects[ctools][version] = "1.3"

projects[cck_phone][version] = "1.x-dev"

projects[ccl][version] = "1.5"

projects[node_clone][version] = "1.0-rc1"

projects[conditional_fields][version] = "3.x-dev"

projects[content_access][version] = "1.2-beta2"

projects[context][version] = "3.0-beta7"

projects[context_addassets][version] = "1.0-beta1"

projects[context_admin][version] = "1.2"

projects[context_disable_context][version] = "3.0"

projects[context_mobile_detect][version] = "1.3"

projects[cron_debug][version] = "1.2"

projects[custom_add_another][version] = "1.0-rc3"

projects[date][version] = "2.6"

projects[db_maintenance][version] = "1.1"

projects[delta][version] = "3.0-beta11"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[ds][version] = "2.4"

projects[email][version] = "1.2"

projects[entity][version] = "1.2"

projects[entityreference][version] = "1.0"

projects[environment_indicator][version] = "1.1"

projects[exclude_node_title][version] = "1.6"

projects[fb_social][version] = "2.0-beta4"

projects[features][version] = "1.0"

projects[field_group][version] = "1.1"

projects[field_permissions][version] = "1.0-beta2"

projects[file_entity][version] = "2.0-alpha1"

projects[filefield_sources][version] = "1.8"

projects[filter_perms][version] = "1.0"

projects[ga_stats][version] = "1.0-beta2"

projects[genpass][version] = "1.0"

projects[geocoder][version] = "1.2"

projects[geofield][version] = "1.2"

projects[geophp][version] = "1.7"

projects[globalredirect][version] = "1.5"

projects[google_analytics][version] = "1.3"

projects[httprl][version] = "1.12"

projects[imagecache_actions][version] = "1.3"

projects[image_url_formatter][version] = "1.0"

projects[imagefield_crop][version] = "1.1"

projects[inline_entity_form][version] = "1.3"

projects[insert][version] = "1.3"

projects[jcarousel][version] = "2.6"

projects[jquery_update][version] = "2.3"

projects[jump_menu][version] = "1.4"

projects[libraries][version] = "2.1"

projects[lightbox2][version] = "1.0-beta1"

projects[link][version] = "1.1"

projects[login_destination][version] = "1.1"

projects[logintoboggan][version] = "1.3"

projects[markdown][version] = "1.2"

projects[masquerade][version] = "1.0-rc5"

projects[media][version] = "1.3"

projects[menu_block][version] = "2.3"

projects[module_filter][version] = "1.8"

projects[multiupload_filefield_widget][version] = "1.11"

projects[omega_tools][version] = "3.0-rc4"

projects[openlayers][version] = "2.0-beta7"

projects[override_node_options][version] = "1.12"

projects[page_title][version] = "2.7"

projects[pathauto][version] = "1.2"

projects[phone][version] = "1.x-dev"

projects[proj4js][version] = "1.2"

projects[publishcontent][version] = "1.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pw_admin][download][type] = ""
projects[pw_admin][download][url] = ""
projects[pw_admin][type] = "module"
projects[pw_admin][version] = "2.61"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pw_cl][download][type] = ""
projects[pw_cl][download][url] = ""
projects[pw_cl][type] = "module"
projects[pw_cl][version] = "2.01"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pw_clients][download][type] = ""
projects[pw_clients][download][url] = ""
projects[pw_clients][type] = "module"
projects[pw_clients][version] = "1.0-alpha"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pw_display][download][type] = ""
projects[pw_display][download][url] = ""
projects[pw_display][type] = "module"
projects[pw_display][version] = "1.6"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pw_editorial][download][type] = ""
projects[pw_editorial][download][url] = ""
projects[pw_editorial][type] = "module"
projects[pw_editorial][version] = "2.92"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pw_la][download][type] = ""
projects[pw_la][download][url] = ""
projects[pw_la][type] = "module"
projects[pw_la][version] = "2.71"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pw_vars][download][type] = ""
projects[pw_vars][download][url] = ""
projects[pw_vars][type] = "module"
projects[pw_vars][version] = "1.22"

projects[realname][version] = "1.1"

projects[redirect][version] = "1.0-rc1"

projects[rules][version] = "2.3"

projects[scheduler][version] = "1.1"

projects[schema][version] = "1.0-rc1"

projects[scribd_filter][version] = "1.3"

projects[search404][version] = "1.3"

projects[securepages][version] = "1.0-beta1"

projects[security_review][version] = "1.0"

projects[simplehtmldom][version] = "1.12"

projects[smartcrop][version] = "1.0-beta2"

projects[stringoverrides][version] = "1.8"

projects[strongarm][version] = "2.0"

projects[taxonomy_menu][version] = "1.4"

projects[taxonomy_orphanage][version] = "1.1"

projects[token][version] = "1.5"

projects[user_role_field][version] = "1.1"

projects[view_unpublished][version] = "1.1"

projects[views][version] = "3.7"

projects[views_grouped_table][version] = "1.1"

projects[views_nodes_split][version] = "1.0-rc1"

projects[views_php][version] = "1.x-dev"

projects[views_slideshow][version] = "3.0"

projects[views_tree][version] = "2.0"

projects[webform][version] = "3.19"

projects[webform_phone][version] = "1.13"

projects[wysiwyg][version] = "2.2"

; Themes
projects[omega][version] = "3.1"

;PW   ; Please fill the following out. Type may be one of get, git, bzr or svn,
;PW   ; and url is the url of the download.
;PW   projects[Pennywise][download][type] = ""
;PW   projects[Pennywise][download][url] = ""
;PW   projects[Pennywise][type] = "theme"
;PW   projects[Pennywise][version] = "1.x"
;PW
;PW   ; Modules
;PW   ; Please fill the following out. Type may be one of get, git, bzr or svn,
;PW   ; and url is the url of the download.
;PW   projects[ad_payment][download][type] = ""
;PW   projects[ad_payment][download][url] = ""
;PW   projects[ad_payment][type] = "module"
;PW
;PW   ; Please fill the following out. Type may be one of get, git, bzr or svn,
;PW   ; and url is the url of the download.
;PW   projects[adworks][download][type] = ""
;PW   projects[adworks][download][url] = ""
;PW   projects[adworks][type] = "module"
;PW
;PW   ; Please fill the following out. Type may be one of get, git, bzr or svn,
;PW   ; and url is the url of the download.
;PW   projects[pennywise][download][type] = ""
;PW   projects[pennywise][download][url] = ""
;PW   projects[pennywise][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "zip"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.2/ckeditor_4.2_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[dompdf][download][type] = "zip"
libraries[dompdf][download][url] = "https://dompdf.googlecode.com/files/dompdf_0-6-0_beta3.zip"
libraries[dompdf][directory_name] = "dompdf"
libraries[dompdf][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[facebook-php-sdk][download][type] = "git"
libraries[facebook-php-sdk][download][url] = "https://github.com/facebook/facebook-php-sdk/archive/master.zip"
libraries[facebook-php-sdk][directory_name] = "facebook-php-sdk"
libraries[facebook-php-sdk][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Jcrop][download][type] = "zip"
libraries[Jcrop][download][url] = "https://github.com/tapmodo/Jcrop/zipball/v0.9.12"
libraries[Jcrop][directory_name] = "Jcrop"
libraries[Jcrop][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-1.6.4][download][type] = ""
libraries[jquery-1.6.4][download][url] = "http://code.jquery.com/jquery-1.6.4.min.js"
libraries[jquery-1.6.4][directory_name] = "jquery-1.6.4"
libraries[jquery-1.6.4][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-mobile-1.3.1][download][type] = ""
libraries[jquery-mobile-1.3.1][download][url] = "http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"
libraries[jquery-mobile-1.3.1][directory_name] = "jquery-mobile-1.3.1"
libraries[jquery-mobile-1.3.1][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = "http://malsup.github.io/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.quicksand][download][type] = "js"
libraries[jquery.quicksand][download][url] = "https://raw.github.com/razorjack/quicksand/v1.3/jquery.quicksand.js"
libraries[jquery.quicksand][directory_name] = "jquery.quicksand"
libraries[jquery.quicksand][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = ""
libraries[json2][download][url] = "https://jquery-json.googlecode.com/files/jquery.json-2.2.min.js"
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = "gz"
libraries[lessphp][download][url] = "http://leafo.net/lessphp/src/lessphp-0.4.0.tar.gz"
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; libraries[masonry][download][type] = ""
libraries[masonry][download][url] = "http://masonry.desandro.com/masonry.pkgd.min.js"
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[php-cloudfiles][download][type] = ""
libraries[php-cloudfiles][download][url] = ""
libraries[php-cloudfiles][directory_name] = "php-cloudfiles"
libraries[php-cloudfiles][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[plupload][download][type] = "zip"
libraries[plupload][download][url] = "http://plupload.com/downloads/plupload_2_0_0beta.1308111349.zip"
libraries[plupload][directory_name] = "plupload"
libraries[plupload][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = "zip"
libraries[tinymce][download][url] = "http://download.moxiecode.com/tinymce/tinymce_4.0.4.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

